version: '3.8'

services:
  # API 服務
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./client_secret.json:/app/client_secret.json
      - ./.env:/app/.env
    environment:
      - EMAIL_TOKEN_PATH=/app/token.json
    depends_on:
      - db
      - redis
      - minio
    restart: always

  # PostgreSQL 資料庫
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
    ports:
      - "5432:5432"

  # Redis 快取與任務佇列
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # Minio (S3 相容儲存服務)
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data: 